[2024-04-04T00:05:36.655+0000] {processor.py:161} INFO - Started process (PID=99199) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:05:36.658+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py for tasks to queue
[2024-04-04T00:05:36.659+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:05:36.658+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:05:49.086+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:05:49.081+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py", line 125, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-04T00:05:49.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:05:49.433+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py took 12.786 seconds
[2024-04-04T00:06:43.172+0000] {processor.py:161} INFO - Started process (PID=99578) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:06:43.176+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py for tasks to queue
[2024-04-04T00:06:43.177+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:06:43.176+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:06:51.521+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:06:51.518+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py", line 125, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-04T00:06:51.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:06:51.557+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py took 8.391 seconds
[2024-04-04T00:07:49.965+0000] {processor.py:161} INFO - Started process (PID=99968) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:07:49.968+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py for tasks to queue
[2024-04-04T00:07:49.969+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:07:49.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:07:59.532+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:07:59.528+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py", line 125, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-04T00:07:59.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:07:59.564+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py took 9.613 seconds
[2024-04-04T00:08:57.329+0000] {processor.py:161} INFO - Started process (PID=100373) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:08:57.331+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py for tasks to queue
[2024-04-04T00:08:57.333+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:08:57.332+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:09:05.847+0000] {logging_mixin.py:188} INFO - [2024-04-04T00:09:05.844+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py", line 125, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-04T00:09:05.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py
[2024-04-04T00:09:05.876+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_original.py took 8.552 seconds
