[2024-04-03T20:45:47.770+0000] {processor.py:161} INFO - Started process (PID=82303) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:45:47.772+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py for tasks to queue
[2024-04-03T20:45:47.773+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:45:47.773+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:45:56.911+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:45:56.907+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:45:56.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:45:56.945+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py took 9.180 seconds
[2024-04-03T20:47:05.386+0000] {processor.py:161} INFO - Started process (PID=82877) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:47:05.389+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py for tasks to queue
[2024-04-03T20:47:05.391+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:47:05.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:47:14.148+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:47:14.144+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:47:14.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py
[2024-04-03T20:47:14.181+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new copy.py took 8.800 seconds
