[2024-04-03T20:45:37.857+0000] {processor.py:161} INFO - Started process (PID=82134) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:45:37.860+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:45:37.862+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:45:37.861+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:45:47.034+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:45:47.028+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:45:47.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:45:47.424+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 9.575 seconds
[2024-04-03T20:46:55.233+0000] {processor.py:161} INFO - Started process (PID=82745) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:46:55.236+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:46:55.238+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:46:55.237+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:47:04.138+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:47:04.134+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:47:04.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:47:04.180+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 8.952 seconds
[2024-04-03T20:47:37.771+0000] {processor.py:161} INFO - Started process (PID=83098) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:47:37.774+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:47:37.775+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:47:37.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:47:46.615+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:47:46.611+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:47:46.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:47:46.652+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 8.886 seconds
[2024-04-03T20:48:38.886+0000] {processor.py:161} INFO - Started process (PID=83318) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:48:38.889+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:48:38.891+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:48:38.890+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:48:48.194+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:48:48.190+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:48:48.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:48:48.230+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 9.351 seconds
[2024-04-03T20:49:49.701+0000] {processor.py:161} INFO - Started process (PID=83659) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:49:49.704+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:49:49.706+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:49:49.705+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:49:58.327+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:49:58.321+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:49:58.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:49:58.377+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 8.681 seconds
[2024-04-03T20:50:50.565+0000] {processor.py:161} INFO - Started process (PID=83932) to work on /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:50:50.567+0000] {processor.py:830} INFO - Processing file /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py for tasks to queue
[2024-04-03T20:50:50.568+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:50:50.568+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:50:59.058+0000] {logging_mixin.py:188} INFO - [2024-04-03T20:50:59.054+0000] {dagbag.py:350} ERROR - Failed to import: /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
Traceback (most recent call last):
  File "/home/datatalks_jan/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py", line 126, in <module>
    'retry_delay': timedelta(minutes=5),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-04-03T20:50:59.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py
[2024-04-03T20:50:59.093+0000] {processor.py:183} INFO - Processing /home/datatalks_jan/Data_Eden/3_airflow_demo/airflow/dags/dag_spark_multi_source_ETL_new.py took 8.533 seconds
