[2024-02-21T19:07:30.532+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_parquet_task manual__2024-02-21T19:07:24.553866+00:00 [queued]>
[2024-02-21T19:07:30.549+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.download_parquet_task manual__2024-02-21T19:07:24.553866+00:00 [queued]>
[2024-02-21T19:07:30.550+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-21T19:07:30.579+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_parquet_task> on 2024-02-21 19:07:24.553866+00:00
[2024-02-21T19:07:30.591+0000] {standard_task_runner.py:60} INFO - Started process 490 to run task
[2024-02-21T19:07:30.599+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_parquet_task', 'manual__2024-02-21T19:07:24.553866+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpihv70xtq']
[2024-02-21T19:07:30.602+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask download_parquet_task
[2024-02-21T19:07:30.703+0000] {task_command.py:423} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_parquet_task manual__2024-02-21T19:07:24.553866+00:00 [running]> on host e489b6887f30
[2024-02-21T19:07:30.879+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='download_parquet_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-21T19:07:24.553866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-21T19:07:24.553866+00:00'
[2024-02-21T19:07:31.527+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_dag.py", line 29, in download_file
    with open(local_file_path, 'wb') as f:
NameError: name 'local_file_path' is not defined
[2024-02-21T19:07:31.539+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_dag, task_id=download_parquet_task, execution_date=20240221T190724, start_date=20240221T190730, end_date=20240221T190731
[2024-02-21T19:07:31.556+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task download_parquet_task (name 'local_file_path' is not defined; 490)
[2024-02-21T19:07:31.594+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-21T19:07:31.624+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
